import Head from "next/head";
import { Inter } from "next/font/google";
import { BrowserRouter } from "react-router-dom";
import { useState, useEffect } from "react";
import RoutePage from "@/routes";
import { getAppDetial } from "@/services";
import { decrypt, encrypt, get_token } from "@/utils/helpers";
import { bannerAry } from "../../public/assets/sampleArry";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [tenantName, setTenantName] = useState(null)

    useEffect(() => {
      const url = window.location.href;
      const tenantName = url.split(".local")[0]
      fetchAppDetail(tenantName+'/');
    }, [])

    const fetchAppDetail = async (tenantName) =>{ 
      const token = get_token()
      const formData = {
        'domain': tenantName
      }
      const response_content_service = await getAppDetial(encrypt(JSON.stringify(formData),token))
      const encryptData = response_content_service.data;
      decrypt(encryptData, token)
    }

  return (
    <>
      <Head>
        <title>EduCrypt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <!-- Bootstrap CDN --> */}

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
          crossorigin
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
          crossorigin
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossorigin
        ></script>

        {/* <!-- Google Font --> */}
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />

        {/* <!-- Font Awesome CDN --> */}
        <link
          rel="stylesheet"
          href="path/to/font-awesome/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />

        {/* <!-- Owl-Carousel --> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
      </Head>
      {/* <BrowserRouter> */}
        <RoutePage tenantName={tenantName} />
      {/* </BrowserRouter> */}
    </>
  );
}
